reset()

println("Bonjour le monde !")
println()
print("Quel est ton nom ? ")
color(18)
$nom = input()
color(24)
print("Quel est ton age ? ")
color(18)
$age = int(input())

color(24)
println()
println("Bonjour ", $nom, " !")
$delta = random(2, 99)
println("Dans ", $delta, " ans, tu auras ", $delta + $age, " ans.")